[build]
  command = "pnpm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--version"
  PNPM_FLAGS = "--store=node_modules/.pnpm-store"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  directory = ".netlify/functions"

# Redirect all non-admin routes to Next.js
[[redirects]]
  from = "/admin/*"
  to = "/404.html"
  status = 404

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/nextjs/:splat"
  status = 200

# Headers for API routes
[[headers]]
  for = "/api/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff" 